version: '3.7'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=commerce
    volumes:
      - commerce_pg_data:/bitnami/postgresql

volumes:
  commerce_pg_data: